// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: p2p.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	P2PChatService_ReceiveMessage_FullMethodName               = "/p2p.P2PChatService/ReceiveMessage"
	P2PChatService_Ping_FullMethodName                         = "/p2p.P2PChatService/Ping"
	P2PChatService_GetPeerInfo_FullMethodName                  = "/p2p.P2PChatService/GetPeerInfo"
	P2PChatService_ReceiveVideoCallOffer_FullMethodName        = "/p2p.P2PChatService/ReceiveVideoCallOffer"
	P2PChatService_ReceiveVideoCallAnswer_FullMethodName       = "/p2p.P2PChatService/ReceiveVideoCallAnswer"
	P2PChatService_ReceiveVideoCallICECandidate_FullMethodName = "/p2p.P2PChatService/ReceiveVideoCallICECandidate"
	P2PChatService_ReceiveVideoCallHangup_FullMethodName       = "/p2p.P2PChatService/ReceiveVideoCallHangup"
	P2PChatService_ReceiveFile_FullMethodName                  = "/p2p.P2PChatService/ReceiveFile"
)

// P2PChatServiceClient is the client API for P2PChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The p2p chat service is the main node to node service for communicating with other nodes and exposes similar methods
type P2PChatServiceClient interface {
	// RPC for handling when we recieve message from a node.
	ReceiveMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageAck, error)
	// RPC for handling a ping.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// RPC for getting another peers info.
	GetPeerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerInfo, error)
	// Video call signaling RPCs — backend acts as passthrough, routing these between peers.
	ReceiveVideoCallOffer(ctx context.Context, in *VideoCallOffer, opts ...grpc.CallOption) (*VideoCallAck, error)
	ReceiveVideoCallAnswer(ctx context.Context, in *VideoCallAnswer, opts ...grpc.CallOption) (*VideoCallAck, error)
	ReceiveVideoCallICECandidate(ctx context.Context, in *VideoCallICECandidate, opts ...grpc.CallOption) (*VideoCallAck, error)
	ReceiveVideoCallHangup(ctx context.Context, in *VideoCallHangup, opts ...grpc.CallOption) (*VideoCallAck, error)
	// File transfer — client-streaming so large files are sent in chunks.
	ReceiveFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileTransferAck], error)
}

type p2PChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PChatServiceClient(cc grpc.ClientConnInterface) P2PChatServiceClient {
	return &p2PChatServiceClient{cc}
}

func (c *p2PChatServiceClient) ReceiveMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageAck)
	err := c.cc.Invoke(ctx, P2PChatService_ReceiveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, P2PChatService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) GetPeerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerInfo)
	err := c.cc.Invoke(ctx, P2PChatService_GetPeerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) ReceiveVideoCallOffer(ctx context.Context, in *VideoCallOffer, opts ...grpc.CallOption) (*VideoCallAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoCallAck)
	err := c.cc.Invoke(ctx, P2PChatService_ReceiveVideoCallOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) ReceiveVideoCallAnswer(ctx context.Context, in *VideoCallAnswer, opts ...grpc.CallOption) (*VideoCallAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoCallAck)
	err := c.cc.Invoke(ctx, P2PChatService_ReceiveVideoCallAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) ReceiveVideoCallICECandidate(ctx context.Context, in *VideoCallICECandidate, opts ...grpc.CallOption) (*VideoCallAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoCallAck)
	err := c.cc.Invoke(ctx, P2PChatService_ReceiveVideoCallICECandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) ReceiveVideoCallHangup(ctx context.Context, in *VideoCallHangup, opts ...grpc.CallOption) (*VideoCallAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoCallAck)
	err := c.cc.Invoke(ctx, P2PChatService_ReceiveVideoCallHangup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) ReceiveFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileTransferAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2PChatService_ServiceDesc.Streams[0], P2PChatService_ReceiveFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FileTransferAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PChatService_ReceiveFileClient = grpc.ClientStreamingClient[FileChunk, FileTransferAck]

// P2PChatServiceServer is the server API for P2PChatService service.
// All implementations must embed UnimplementedP2PChatServiceServer
// for forward compatibility.
//
// The p2p chat service is the main node to node service for communicating with other nodes and exposes similar methods
type P2PChatServiceServer interface {
	// RPC for handling when we recieve message from a node.
	ReceiveMessage(context.Context, *Message) (*MessageAck, error)
	// RPC for handling a ping.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// RPC for getting another peers info.
	GetPeerInfo(context.Context, *Empty) (*PeerInfo, error)
	// Video call signaling RPCs — backend acts as passthrough, routing these between peers.
	ReceiveVideoCallOffer(context.Context, *VideoCallOffer) (*VideoCallAck, error)
	ReceiveVideoCallAnswer(context.Context, *VideoCallAnswer) (*VideoCallAck, error)
	ReceiveVideoCallICECandidate(context.Context, *VideoCallICECandidate) (*VideoCallAck, error)
	ReceiveVideoCallHangup(context.Context, *VideoCallHangup) (*VideoCallAck, error)
	// File transfer — client-streaming so large files are sent in chunks.
	ReceiveFile(grpc.ClientStreamingServer[FileChunk, FileTransferAck]) error
	mustEmbedUnimplementedP2PChatServiceServer()
}

// UnimplementedP2PChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedP2PChatServiceServer struct{}

func (UnimplementedP2PChatServiceServer) ReceiveMessage(context.Context, *Message) (*MessageAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveMessage not implemented")
}
func (UnimplementedP2PChatServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedP2PChatServiceServer) GetPeerInfo(context.Context, *Empty) (*PeerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeerInfo not implemented")
}
func (UnimplementedP2PChatServiceServer) ReceiveVideoCallOffer(context.Context, *VideoCallOffer) (*VideoCallAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveVideoCallOffer not implemented")
}
func (UnimplementedP2PChatServiceServer) ReceiveVideoCallAnswer(context.Context, *VideoCallAnswer) (*VideoCallAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveVideoCallAnswer not implemented")
}
func (UnimplementedP2PChatServiceServer) ReceiveVideoCallICECandidate(context.Context, *VideoCallICECandidate) (*VideoCallAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveVideoCallICECandidate not implemented")
}
func (UnimplementedP2PChatServiceServer) ReceiveVideoCallHangup(context.Context, *VideoCallHangup) (*VideoCallAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveVideoCallHangup not implemented")
}
func (UnimplementedP2PChatServiceServer) ReceiveFile(grpc.ClientStreamingServer[FileChunk, FileTransferAck]) error {
	return status.Error(codes.Unimplemented, "method ReceiveFile not implemented")
}
func (UnimplementedP2PChatServiceServer) mustEmbedUnimplementedP2PChatServiceServer() {}
func (UnimplementedP2PChatServiceServer) testEmbeddedByValue()                        {}

// UnsafeP2PChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P2PChatServiceServer will
// result in compilation errors.
type UnsafeP2PChatServiceServer interface {
	mustEmbedUnimplementedP2PChatServiceServer()
}

func RegisterP2PChatServiceServer(s grpc.ServiceRegistrar, srv P2PChatServiceServer) {
	// If the following call panics, it indicates UnimplementedP2PChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&P2PChatService_ServiceDesc, srv)
}

func _P2PChatService_ReceiveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).ReceiveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_ReceiveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).ReceiveMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_GetPeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).GetPeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_GetPeerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).GetPeerInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_ReceiveVideoCallOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoCallOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).ReceiveVideoCallOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_ReceiveVideoCallOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).ReceiveVideoCallOffer(ctx, req.(*VideoCallOffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_ReceiveVideoCallAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoCallAnswer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).ReceiveVideoCallAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_ReceiveVideoCallAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).ReceiveVideoCallAnswer(ctx, req.(*VideoCallAnswer))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_ReceiveVideoCallICECandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoCallICECandidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).ReceiveVideoCallICECandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_ReceiveVideoCallICECandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).ReceiveVideoCallICECandidate(ctx, req.(*VideoCallICECandidate))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_ReceiveVideoCallHangup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoCallHangup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).ReceiveVideoCallHangup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_ReceiveVideoCallHangup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).ReceiveVideoCallHangup(ctx, req.(*VideoCallHangup))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_ReceiveFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(P2PChatServiceServer).ReceiveFile(&grpc.GenericServerStream[FileChunk, FileTransferAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PChatService_ReceiveFileServer = grpc.ClientStreamingServer[FileChunk, FileTransferAck]

// P2PChatService_ServiceDesc is the grpc.ServiceDesc for P2PChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P2PChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.P2PChatService",
	HandlerType: (*P2PChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMessage",
			Handler:    _P2PChatService_ReceiveMessage_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _P2PChatService_Ping_Handler,
		},
		{
			MethodName: "GetPeerInfo",
			Handler:    _P2PChatService_GetPeerInfo_Handler,
		},
		{
			MethodName: "ReceiveVideoCallOffer",
			Handler:    _P2PChatService_ReceiveVideoCallOffer_Handler,
		},
		{
			MethodName: "ReceiveVideoCallAnswer",
			Handler:    _P2PChatService_ReceiveVideoCallAnswer_Handler,
		},
		{
			MethodName: "ReceiveVideoCallICECandidate",
			Handler:    _P2PChatService_ReceiveVideoCallICECandidate_Handler,
		},
		{
			MethodName: "ReceiveVideoCallHangup",
			Handler:    _P2PChatService_ReceiveVideoCallHangup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveFile",
			Handler:       _P2PChatService_ReceiveFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "p2p.proto",
}
