// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: p2p.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	P2PChatService_ReceiveMessage_FullMethodName = "/p2p.P2PChatService/ReceiveMessage"
	P2PChatService_Ping_FullMethodName           = "/p2p.P2PChatService/Ping"
	P2PChatService_GetPeerInfo_FullMethodName    = "/p2p.P2PChatService/GetPeerInfo"
	P2PChatService_StreamMessages_FullMethodName = "/p2p.P2PChatService/StreamMessages"
)

// P2PChatServiceClient is the client API for P2PChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The p2p chat service is the main node to node service for communicating with other nodes and exposes similar methods
type P2PChatServiceClient interface {
	// RPC for handling when we recieve message from a node.
	ReceiveMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageAck, error)
	// RPC for handling a ping.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// RPC for getting another peers info.
	GetPeerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerInfo, error)
	// RPC for streaming messages to other nodes.
	StreamMessages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error)
}

type p2PChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PChatServiceClient(cc grpc.ClientConnInterface) P2PChatServiceClient {
	return &p2PChatServiceClient{cc}
}

func (c *p2PChatServiceClient) ReceiveMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageAck)
	err := c.cc.Invoke(ctx, P2PChatService_ReceiveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, P2PChatService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) GetPeerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerInfo)
	err := c.cc.Invoke(ctx, P2PChatService_GetPeerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PChatServiceClient) StreamMessages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2PChatService_ServiceDesc.Streams[0], P2PChatService_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Message]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PChatService_StreamMessagesClient = grpc.ServerStreamingClient[Message]

// P2PChatServiceServer is the server API for P2PChatService service.
// All implementations must embed UnimplementedP2PChatServiceServer
// for forward compatibility.
//
// The p2p chat service is the main node to node service for communicating with other nodes and exposes similar methods
type P2PChatServiceServer interface {
	// RPC for handling when we recieve message from a node.
	ReceiveMessage(context.Context, *Message) (*MessageAck, error)
	// RPC for handling a ping.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// RPC for getting another peers info.
	GetPeerInfo(context.Context, *Empty) (*PeerInfo, error)
	// RPC for streaming messages to other nodes.
	StreamMessages(*Empty, grpc.ServerStreamingServer[Message]) error
	mustEmbedUnimplementedP2PChatServiceServer()
}

// UnimplementedP2PChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedP2PChatServiceServer struct{}

func (UnimplementedP2PChatServiceServer) ReceiveMessage(context.Context, *Message) (*MessageAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveMessage not implemented")
}
func (UnimplementedP2PChatServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedP2PChatServiceServer) GetPeerInfo(context.Context, *Empty) (*PeerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeerInfo not implemented")
}
func (UnimplementedP2PChatServiceServer) StreamMessages(*Empty, grpc.ServerStreamingServer[Message]) error {
	return status.Error(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedP2PChatServiceServer) mustEmbedUnimplementedP2PChatServiceServer() {}
func (UnimplementedP2PChatServiceServer) testEmbeddedByValue()                        {}

// UnsafeP2PChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P2PChatServiceServer will
// result in compilation errors.
type UnsafeP2PChatServiceServer interface {
	mustEmbedUnimplementedP2PChatServiceServer()
}

func RegisterP2PChatServiceServer(s grpc.ServiceRegistrar, srv P2PChatServiceServer) {
	// If the following call panics, it indicates UnimplementedP2PChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&P2PChatService_ServiceDesc, srv)
}

func _P2PChatService_ReceiveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).ReceiveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_ReceiveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).ReceiveMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_GetPeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PChatServiceServer).GetPeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PChatService_GetPeerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PChatServiceServer).GetPeerInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PChatService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P2PChatServiceServer).StreamMessages(m, &grpc.GenericServerStream[Empty, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PChatService_StreamMessagesServer = grpc.ServerStreamingServer[Message]

// P2PChatService_ServiceDesc is the grpc.ServiceDesc for P2PChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P2PChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.P2PChatService",
	HandlerType: (*P2PChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMessage",
			Handler:    _P2PChatService_ReceiveMessage_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _P2PChatService_Ping_Handler,
		},
		{
			MethodName: "GetPeerInfo",
			Handler:    _P2PChatService_GetPeerInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _P2PChatService_StreamMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "p2p.proto",
}
